### ISSUE TITLE
doesn't work, asks for /root/letsencrypt/letsencrypt-auto

### ISSUE THREAD

**Issue by Chrescht** [VojtechMyslivec/letsencrypt-zimbra#20]
obtain-and-deploy-letsencrypt-cert.sh[err]: Letsencrypt tool '/root/letsencrypt/letsencrypt-auto' isn't executable file.

I don't even have this file..

**Comment by VojtechMyslivec** [comment]
You must to install/download *letsencrypt-auto* (alias [certbot](https://github.com/certbot/certbot)) tool. It is mentioned in the *usage* of the script.

You can specify the path to this tool in variable `letsencrypt` if you install it in another directory.

I am working on configuration file in the `parameters` branch. You can use this brnach and edit just the config file (instead of changing vars in main script).

**Comment by Chrescht** [comment]
I would not consider this to be a question but an improvement :-)
Could you add a small "installation" section in your README.md? I think this would be quite helpful as this is common practice.

**Comment by VojtechMyslivec** [comment]
Yes it would be. I have already create a TODO about the installation notes in #3. So I will close this one to not hold duplicate issues open, ok?
